### ISSUE TITLE
Error: No element indexed by 0

### ISSUE THREAD

**Issue by scottcorgan** [Jam3/hihat#23]
Running the command: 
`hihat __test__/state/*.js __test__/sdk/*.js __test__/serialize/*.js -- -t [babelify --stage 0] -p tap-dev-tool`

Throws the following error:
```
Error: No element indexed by 0
    at ArraySet_at [as at] (/Users/scottcorgan/www/laurelandwolf/data/node_modules/browserify/node_modules/browser-pack/node_modules/combine-source-map/node_modules/source-map/lib/source-map/array-set.js:93:11)
    at SourceMapConsumer.<anonymous> (/Users/scottcorgan/www/laurelandwolf/data/node_modules/browserify/node_modules/browser-pack/node_modules/combine-source-map/node_modules/source-map/lib/source-map/source-map-consumer.js:147:79)
    at Array.map (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (/Users/scottcorgan/www/laurelandwolf/data/node_modules/browserify/node_modules/browser-pack/node_modules/combine-source-map/node_modules/source-map/lib/source-map/source-map-consumer.js:146:16)
    at module.exports (/Users/scottcorgan/www/laurelandwolf/data/node_modules/browserify/node_modules/browser-pack/node_modules/combine-source-map/lib/mappings-from-map.js:13:12)
    at Combiner._addExistingMap (/Users/scottcorgan/www/laurelandwolf/data/node_modules/browserify/node_modules/browser-pack/node_modules/combine-source-map/index.js:70:18)
    at Combiner.addFile (/Users/scottcorgan/www/laurelandwolf/data/node_modules/browserify/node_modules/browser-pack/node_modules/combine-source-map/index.js:113:49)
    at DestroyableTransform.write [as _transform] (/Users/scottcorgan/www/laurelandwolf/data/node_modules/browserify/node_modules/browser-pack/index.js:63:23)
    at DestroyableTransform.Transform._read (/Users/scottcorgan/www/laurelandwolf/data/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/scottcorgan/www/laurelandwolf/data/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/scottcorgan/www/laurelandwolf/data/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:279:12)
    at writeOrBuffer (/Users/scottcorgan/www/laurelandwolf/data/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:266:5)
    at DestroyableTransform.Writable.write (/Users/scottcorgan/www/laurelandwolf/data/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:211:11)
    at DestroyableTransform.ondata (/Users/scottcorgan/www/laurelandwolf/data/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:572:20)
    at emitOne (events.js:77:13)
    at DestroyableTransform.emit (events.js:169:7)
    at readableAddChunk (/Users/scottcorgan/www/laurelandwolf/data/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:195:16)
    at DestroyableTransform.Readable.push (/Users/scottcorgan/www/laurelandwolf/data/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:162:10)
    at DestroyableTransform.Transform.push (/Users/scottcorgan/www/laurelandwolf/data/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at afterTransform (/Users/scottcorgan/www/laurelandwolf/data/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:101:12)
    at TransformState.afterTransform (/Users/scottcorgan/www/laurelandwolf/data/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at DestroyableTransform.noop [as _transform] (/Users/scottcorgan/www/laurelandwolf/data/node_modules/browserify/node_modules/through2/through2.js:26:3)
    at DestroyableTransform.Transform._read (/Users/scottcorgan/www/laurelandwolf/data/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/scottcorgan/www/laurelandwolf/data/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/scottcorgan/www/laurelandwolf/data/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:279:12)
    at writeOrBuffer (/Users/scottcorgan/www/laurelandwolf/data/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:266:5)
    at DestroyableTransform.Writable.write (/Users/scottcorgan/www/laurelandwolf/data/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:211:11)
    at DestroyableTransform._transform (/Users/scottcorgan/www/laurelandwolf/data/node_modules/browserify/node_modules/browser-pack/index.js:25:44)
    at DestroyableTransform.Transform._read (/Users/scottcorgan/www/laurelandwolf/data/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/scottcorgan/www/laurelandwolf/data/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at Labeled.Pipeline._write (/Users/scottcorgan/www/laurelandwolf/data/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/index.js:73:22)
    at doWrite (/Users/scottcorgan/www/laurelandwolf/data/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_writable.js:279:1

...
```

**Comment by yoshuawuyts** [comment]
This is rough to track down. Could you try narrow the scope of the error down / create a repro? Thanks!

**Comment by scottcorgan** [comment]
Ya, it's very rough to track down. I uninstalled, restarted, and reinstalled. That seemed to fix it. Not quite sure what was going on.
