### ISSUE TITLE
`ENOENT error` on OS X npm 3.6

### ISSUE THREAD

**Issue by archywillhe** [Jam3/hihat#36]
after `npm install -g hihat` I try running `hihat` in my terminal and get the following error:

```
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/hihat/node_modules/electron-prebuilt/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.<anonymous> (/usr/local/lib/node_modules/hihat/node_modules/electron-prebuilt/index.js:4:42)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
```

**Comment by archywillhe** [comment]
Turned out it is because  when I do `npm install -g hihat` the first time it didn't finish the post installation of electron (for some network reason). (And when I do `npm install -g hihat` the second time, no error is thrown and I thought the post-installation was done)

Solution: remove & reinstall hihat.
